export const coinList  = [
	{ label: 'Mais populares', options: [
		{ value: 'USD', label: 'Dólar Americano', symbol: '$' },
		{ value: 'EUR', label: 'Euro', symbol: '€' },
		{ value: 'GBP', label: 'Libra esterlina[C]', symbol: '£' },
		{ value: 'BRL', label: 'Real Brasileiro', symbol: 'R$' },
	]},
	{ label: 'Criptomoedas', options: [
		{ value: 'BTC', label: 'Bitcoin', symbol: '₿' },
	]},
	{ value: 'AED', label: 'Dirame dos Emirados Árabes Unidos', symbol: 'د.إ' },
	{ value: 'AFN', label: 'Afegane afegão', symbol: '؋' },
	{ value: 'ALL', label: 'Lek albanês', symbol: 'L' },
	{ value: 'AMD', label: 'Dram arménio', symbol: '' },
	{ value: 'ANG', label: 'Florim antilhano', symbol: 'ƒ' },
	{ value: 'AOA', label: 'Kwanza angolano', symbol: 'Kz' },
	{ value: 'ARS', label: 'Peso argentino', symbol: '$' },
	{ value: 'AUD', label: 'Dólar australiano', symbol: '$' },
	{ value: 'AWG', label: 'Florim arubano', symbol: 'ƒ' },
	{ value: 'AZN', label: 'Manat azerbaijano', symbol: '' },
	{ value: 'BAM', label: 'Marco convertível da Bósnia e Herzegovina', symbol: 'KM' },
	{ value: 'BBD', label: 'Dólar dos Barbados', symbol: '$' },
	{ value: 'BDT', label: 'Taka bangladexense', symbol: '৳' },
	{ value: 'BGN', label: 'Lev búlgaro', symbol: 'лв' },
	{ value: 'BHD', label: 'Dinar barenita', symbol: '.د.ب' },
	{ value: 'BIF', label: 'Franco burundiano', symbol: 'Fr' },
	{ value: 'BMD', label: 'Dólar bermudense', symbol: '$' },
	{ value: 'BND', label: 'Dólar do Brunei', symbol: '$' },
	{ value: 'BOB', label: 'Boliviano', symbol: 'Bs.' },
	{ value: 'BSD', label: 'Dólar baamense', symbol: '$' },
	{ value: 'BTN', label: 'Ngultrum butanês', symbol: 'Nu.' },
	{ value: 'BWP', label: 'Pula do Botsuana', symbol: 'P' },
	{ value: 'BYN', label: 'Rublo bielorrusso', symbol: 'Br' },
	{ value: 'BYR', label: 'Rublo bielorrusso', symbol: 'Br' },
	{ value: 'BZD', label: 'Dólar do Belize', symbol: '$' },
	{ value: 'CAD', label: 'Dólar canadiano', symbol: '$' },
	{ value: 'CDF', label: 'Franco congolês', symbol: 'Fr' },
	{ value: 'CHF', label: 'Franco suíço', symbol: 'Fr' },
	{ value: 'CLF', label: 'Unidad de Fomento chileno', symbol: 'UF' },
	{ value: 'CLP', label: 'Peso chileno', symbol: '$' },
	{ value: 'CNY', label: 'Iuane chinês', symbol: '¥ ou 元' },
	{ value: 'COP', label: 'Peso colombiano', symbol: '$' },
	{ value: 'CRC', label: 'Colón costarriquenho', symbol: '₡' },
	{ value: 'CUC', label: 'Peso cubano convertível', symbol: '$' },
	{ value: 'CUP', label: 'Peso cubano', symbol: '$' },
	{ value: 'CVE', label: 'Escudo cabo-verdiano', symbol: 'Esc' },
	{ value: 'CZK', label: 'Coroa checa', symbol: 'Kč' },
	{ value: 'DJF', label: 'Franco jibutiano', symbol: 'Fr' },
	{ value: 'DKK', label: 'Coroa dinamarquesa', symbol: 'kr' },
	{ value: 'DOP', label: 'Peso dominicano', symbol: '$' },
	{ value: 'DZD', label: 'Dinar argelino', symbol: 'د.ج' },
	{ value: 'EGP', label: 'Libra egípcia', symbol: 'ج.م' },
	{ value: 'ERN', label: 'Nakfa eritreia', symbol: 'Nfk' },
	{ value: 'ETB', label: 'Birr etíope', symbol: 'Br' },
	{ value: 'EUR', label: 'Euro', symbol: '€' },
	{ value: 'FJD', label: 'Dólar fijiano', symbol: '$' },
	{ value: 'FKP', label: 'Libra das Ilhas Malvinas', symbol: '£' },
	{ value: 'GEL', label: 'Lari georgiano', symbol: 'ლ' },
	{ value: 'GGP', label: 'Libra de Guernsey', symbol: '£' },
	{ value: 'GHS', label: 'Cedi do Gana', symbol: '₵' },
	{ value: 'GIP', label: 'Libra de Gibraltar', symbol: '£' },
	{ value: 'GMD', label: 'Dalasi gambiano', symbol: 'D' },
	{ value: 'GNF', label: 'Franco guineense', symbol: 'Fr' },
	{ value: 'GTQ', label: 'Quetzal guatemalteco', symbol: 'Q' },
	{ value: 'GYD', label: 'Dólar guianense', symbol: '$' },
	{ value: 'HKD', label: 'Dólar de Honguecongue', symbol: '$' },
	{ value: 'HNL', label: 'Lempira hondurenha', symbol: 'L' },
	{ value: 'HRK', label: 'Kuna croata', symbol: 'kn' },
	{ value: 'HTG', label: 'Gurde haitiano', symbol: 'G' },
	{ value: 'HUF', label: 'Florim húngaro', symbol: 'Ft' },
	{ value: 'IDR', label: 'Rupia indonésia', symbol: 'Rp' },
	{ value: 'ILS', label: 'Novo siclo israelita', symbol: '₪' },
	{ value: 'IMP', label: 'libra Manx', symbol: '£' },
	{ value: 'INR', label: 'Rupia indiana', symbol: '₹' },
	{ value: 'IQD', label: 'Dinar iraquiano', symbol: 'ع.د' },
	{ value: 'IRR', label: 'Rial iraniano', symbol: '﷼' },
	{ value: 'ISK', label: 'Coroa islandesa', symbol: 'kr' },
	{ value: 'JEP', label: 'Libra de Jersey', symbol: '£' },
	{ value: 'JMD', label: 'Dólar jamaicano', symbol: '$' },
	{ value: 'JOD', label: 'Dinar jordano', symbol: 'د.ا' },
	{ value: 'JPY', label: 'Iene japonês', symbol: '¥' },
	{ value: 'KES', label: 'Xelim queniano', symbol: 'Sh' },
	{ value: 'KGS', label: 'Som quirguiz', symbol: 'лв' },
	{ value: 'KHR', label: 'Riel cambojano', symbol: '៛' },
	{ value: 'KMF', label: 'Franco comorense', symbol: 'Fr' },
	{ value: 'KPW', label: 'Won norte-coreano', symbol: '₩' },
	{ value: 'KRW', label: 'Won sul-coreano', symbol: '₩' },
	{ value: 'KWD', label: 'Dinar cuaitiano', symbol: 'د.ك' },
	{ value: 'KYD', label: 'Dólar das Ilhas Caimão', symbol: '$' },
	{ value: 'KZT', label: 'Tengue cazaque', symbol: '₸' },
	{ value: 'LAK', label: 'Kipe lau', symbol: '₭' },
	{ value: 'LBP', label: 'Libra libanesa', symbol: 'ل.ل' },
	{ value: 'LKR', label: 'Rupia do Sri Lanka', symbol: 'රු' },
	{ value: 'LRD', label: 'Dólar liberiano', symbol: '$' },
	{ value: 'LSL', label: 'Loti do Lesoto', symbol: 'L' },
	{ value: 'LYD', label: 'Dinar líbio', symbol: 'ل.د' },
	{ value: 'MAD', label: 'Dirame marroquino', symbol: 'د.م.' },
	{ value: 'MDL', label: 'Leu moldávio', symbol: 'L' },
	{ value: 'MGA', label: 'Ariari malgaxe', symbol: 'Ar' },
	{ value: 'MKD', label: 'Dinar macedónio', symbol: 'ден' },
	{ value: 'MMK', label: 'Kyat de Mianmar', symbol: 'Ks' },
	{ value: 'MNT', label: 'Tugrik mongol', symbol: '₮' },
	{ value: 'MOP', label: 'Pataca macaense', symbol: 'P' },
	{ value: 'MRO', label: 'Uguia mauritana', symbol: 'UM' },
	{ value: 'MUR', label: 'Rupia maurícia', symbol: '₨' },
	{ value: 'MVR', label: 'Rupia maldiva', symbol: '.ރ' },
	{ value: 'MWK', label: 'Kwacha malauiano', symbol: 'MK' },
	{ value: 'MXN', label: 'Peso mexicano', symbol: '$' },
	{ value: 'MYR', label: 'Ringuite malaio', symbol: 'RM' },
	{ value: 'MZN', label: 'Metical moçambicano', symbol: 'MT' },
	{ value: 'NAD', label: 'Dólar namibiano', symbol: '$' },
	{ value: 'NGN', label: 'Naira nigeriano', symbol: '₦' },
	{ value: 'NIO', label: 'Córdoba nicaraguano', symbol: 'C$' },
	{ value: 'NOK', label: 'Coroa norueguesa', symbol: 'kr' },
	{ value: 'NPR', label: 'Rupia nepalesa', symbol: '₨' },
	{ value: 'NZD', label: 'Dólar da Nova Zelândia', symbol: '$' },
	{ value: 'OMR', label: 'Rial omanense', symbol: 'ر.ع.' },
	{ value: 'PAB', label: 'Balboa panamense', symbol: 'B/.' },
	{ value: 'PEN', label: 'Novo sol peruano', symbol: 'S/.' },
	{ value: 'PGK', label: 'Kina papuásia', symbol: 'K' },
	{ value: 'PHP', label: 'Peso filipino', symbol: '₱' },
	{ value: 'PKR', label: 'Rupia paquistanesa', symbol: '₨' },
	{ value: 'PLN', label: 'Zlóti polaco', symbol: 'zł' },
	{ value: 'PYG', label: 'Guarani paraguaio', symbol: '₲' },
	{ value: 'QAR', label: 'Rial catarense', symbol: 'ر.ق' },
	{ value: 'RON', label: 'Leu romeno', symbol: 'lei' },
	{ value: 'RSD', label: 'Dinar sérvio', symbol: 'дин.' },
	{ value: 'RUB', label: 'Rublo russo', symbol: 'р.' },
	{ value: 'RWF', label: 'Franco ruandês', symbol: 'Fr' },
	{ value: 'SAR', label: 'Rial saudita', symbol: 'ر.س' },
	{ value: 'SBD', label: 'Dólar das Ilhas Salomão', symbol: '$' },
	{ value: 'SCR', label: 'Rupia seichelense', symbol: '₨' },
	{ value: 'SDG', label: 'Libra sudanesa', symbol: '£' },
	{ value: 'SEK', label: 'Coroa sueca', symbol: 'kr' },
	{ value: 'SGD', label: 'Dólar de Singapura', symbol: '$' },
	{ value: 'SHP', label: 'Libra de Santa Helena', symbol: '£' },
	{ value: 'SLL', label: 'Leone serra-leonino', symbol: 'Le' },
	{ value: 'SOS', label: 'Xelim somaliano', symbol: 'Sh' },
	{ value: 'SRD', label: 'Dólar surinamês', symbol: '$' },
	{ value: 'STD', label: 'Dobra de São Tomé e Príncipe', symbol: 'Db' },
	{ value: 'SVC', label: 'Colón', symbol: '₡' },
	{ value: 'SYP', label: 'Libra síria', symbol: 'ل.س' },
	{ value: 'SZL', label: 'Lilangeni suazilandês', symbol: 'L' },
	{ value: 'THB', label: 'Baht tailandês', symbol: '฿' },
	{ value: 'TJS', label: 'Somoni tajique', symbol: 'ЅМ' },
	{ value: 'TMT', label: 'Manat turcomeno', symbol: 'm' },
	{ value: 'TND', label: 'Dinar tunisino', symbol: 'د.ت' },
	{ value: 'TOP', label: 'Paʻanga tonganesa', symbol: 'T$' },
	{ value: 'TRY', label: 'Lira turca', symbol: '' },
	{ value: 'TTD', label: 'Dólar de Trindade e Tobago', symbol: '$' },
	{ value: 'TWD', label: 'Novo dólar de Taiuã', symbol: '$' },
	{ value: 'TZS', label: 'Xelim tanzaniano', symbol: 'Sh' },
	{ value: 'UAH', label: 'Grívnia ucraniana', symbol: '₴' },
	{ value: 'UGX', label: 'Xelim ugandês', symbol: 'Sh' },
	{ value: 'UYU', label: 'Peso uruguaio', symbol: '$' },
	{ value: 'UZS', label: 'Som usbeque', symbol: 'лв' },
	{ value: 'VEF', label: 'Bolivar Venezuelano', symbol: 'Bs F' },
	{ value: 'VND', label: 'Dongue vietnamita', symbol: '₫' },
	{ value: 'VUV', label: 'Vatu do Vanuatu', symbol: 'Vt' },
	{ value: 'WST', label: 'Tala samoana', symbol: 'T' },
	{ value: 'XAF', label: 'Franco CFA BEAC', symbol: 'Fr' },
	{ value: 'XAG', label: 'Prata', symbol: 'Prata' },
	{ value: 'XCD', label: 'Dólar das Caraíbas Orientais', symbol: '$' },
	{ value: 'XDR', label: 'Direitos de saque especiais', symbol: 'XDR' },
	{ value: 'XOF', label: 'Franco CFA BCEAO', symbol: 'Fr' },
	{ value: 'XPF', label: 'Franco CFP', symbol: 'Fr' },
	{ value: 'YER', label: 'Rial iemenita', symbol: '﷼' },
	{ value: 'ZAR', label: 'Rand sul-africano', symbol: 'R' },
	{ value: 'ZMK', label: 'Kwacha zambiano', symbol: 'ZK' },
	{ value: 'ZMW', label: 'Kwacha Zambiano', symbol: 'ZK' },
	{ value: 'ZWL', label: 'Dólar do Zimbabwe', symbol: '$' }
]

export default {
	coinList,
}